### ISSUE TITLE
hello lah

### ISSUE THREAD

**Issue by Acceleraizer** [CrimsonTechComp/CompAssignmentsS22#23]
![q1](https://user-images.githubusercontent.com/59228112/164944737-b57199b5-eeb0-4ab8-8b49-252b050b59de.png)

![q2](https://user-images.githubusercontent.com/59228112/164944733-b8bbd323-d6b1-487d-ad5b-562955b11ddb.png)

**Comment by kevinzluo** [comment]
good job
